### PR TITLE
Update Rmd example, make repository Binder-ready

### PR DESCRIPTION
**Pull request by nuest**

### CODE REVIEW

**Comment by nuest** [comment]
## Issue with Rcpp

> library("Rcpp")
Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so)

Tried the answers in https://stackoverflow.com/a/49138437/261210 but with no success.

**Comment by leipzig** [comment]
> ## Issue with Rcpp
> > library("Rcpp")
> > Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
> > unable to load shared object '/srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so':
> > /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /srv/conda/envs/notebook/lib/R/library/Rcpp/libs/Rcpp.so)
> 
> Tried the answers in https://stackoverflow.com/a/49138437/261210 but with no success.

is this a LD_LIBRARY_PATH thing
https://discourse.jupyter.org/t/glibcxx-3-4-26-not-found-from-rstudio/7778/2

**Comment by nuest** [comment]
Yeah, it is! The custom `start` script solved it, will push an update soon.

**Comment by nuest** [comment]
:tada: Three notebookts/scripts work with repo2docker locally - we can wait for the Binder for my repo to work before merging, but this is now ready for review.

image

**Review by leipzig — APPROVED** [review]
looks good. never heard of `here:here`

**Pull request merged**
